# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- task: GitVersion@5
  inputs:
    runtime: 'core'
- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: 'build'
    projects: 'EntityManagement.Core.sln'
    arguments: '--configuration release'
- task: BuildQualityChecks@6
  displayName: 'Build Quality Checks'
  inputs:
    checkWarnings: true
    warningFailOption: 'fixed'
    warningThreshold: '0'
- task: DotNetCoreCLI@2
  displayName: Pack
  inputs:
    command: pack
    packagesToPack: EntityManagement.Core/EntityManagement.Core.csproj
    configuration: release
    versioningScheme: byBuildNumber
- task: NuGetCommand@2
  displayName: 'NuGet push'
  inputs:
    command: push
    nuGetFeedType: external
    publishFeedCredentials: NuGet
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
